string product_version          # 机械臂型号
string controller_version       # 机械臂控制器版本，若为四代控制器，则该字段为"4.0"
string algorithm_info           # 算法库信息
Softwarebuildinfo ctrl_info     # ctrl 层软件信息
string dynamic_info             # 动力学版本（三代）
Softwarebuildinfo plan_info     # plan 层软件信息（三代）
Softwarebuildinfo com_info      # communication 模块软件信息（四代）
Softwarebuildinfo program_info  # 流程图编程模块软件信息（四代）
bool state                      # 查询状态 成功true 失败false
string planversion
string ctrlversion
string kernal1
string kernal2
string productversion
